### PR TITLE
Add scope and handle more general completion system

### PR DESCRIPTION
**Pull request by thisirs**

### CODE REVIEW

**Comment by leafac** [comment]
Hi, @thisirs.

First of all, thanks for using `org-password-manager` and contributing back to it. I have a few questions before I merge your PR:

1. The documentation for the `org-password-manager-scope` variable could mention that it accepts the same values as the `SCOPE` variable for the function `org-map-entries`. This way the user knows their options. What do you think about adding that?
2. The documentation for the same variable `org-password-manager-scope` variable should follow the convention and end in a period `.`. Do you see any reason to don't do that?
3. `org-completing-read` was already the function that was called for people that don't use `ido` (i.e. when `ido-completing-read` isn't defined). Why are you proposing to make `org-completing-read` the default? Wouldn't that prevent `ido` from firing?

Best.

**Comment by thisirs** [comment]
Thanks for writing `org-password-manager`! I was precisely looking for a password manager with these features!

I improved the docstring and mention supported scopes as you suggest.

`org-completing-read` already supports `ido` completion by setting `org-completion-use-ido` to true. See the source of the function `org-icompleting-read`. I am using `helm` and couldn't get it to work with it the way it was implemented...

**Comment by leafac** [comment]
@thisirs, your PR was merged and the updated package should be available through MELPA shortly.

Thanks for your contribution, for taking my suggestion on improving the docstring and for teaching me about `org-completion-use-ido`. I'm changing my configuration now :+1: 

Best.

**Comment by thisirs** [comment]
Great, thanks!

**Pull request merged**
